core:
    resource: "@CoreBundle/Controller"
    type: annotation

login:
    path: /login
    defaults:
        _controller: CoreBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout