core:
    resource: "@CoreBundle/Controller"
    type: annotation

login:
    path: /login
    defaults:
        _controller: CoreBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
