# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        CoreBundle\Entity\User: sha512

    # This part sets the roles hierarchy
    role_hierarchy:
        # Admin inherits amateurs and professionals roles
        ROLE_ADMIN: [ROLE_PRO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username_email

    # Firewall check that we are indeed the one we claim to be
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
            remember_me:
                secret: secret

    access_control:
    #Uncomment this before production. We use this to check that login page -> https.
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }