# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # Todo : Change 'plaintext' by a real encoder
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CoreBundle\Entity\User: plaintext

    # This part sets the roles hierarchy
    role_hierarchy:
        # Admin inherits amateurs and professionals roles
        ROLE_ADMIN: [ROLE_AMATEUR, ROLE_PRO]
        ROLE_SUPER_ADMIN: [ROLE_AMATEUR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # Todo : to delete when we'll use user entity
    providers:
        main:
            entity:
                class: CoreBundle\Entity\User
                property: username

    # Firewall check that we are indeed the one we claim to be
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login

    access_control:
    #Uncomment this before production. We use this to check that login page -> https.
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }