# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.form.registration:
        class: CoreBundle\Form\RegistrationType
        tags:
            - { roles: form.type, name: roles, alias: app_user_registration }
    core_bundle.password_resetting:
        class: CoreBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    core_bundle.profile_edit:
        class: CoreBundle\EventListener\ProfileEditListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    core_bundle.change_password:
        class: CoreBundle\EventListener\ChangePasswordListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
